# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    ignore:
      - dependency-name: "doctrine/annotations"
      - dependency-name: "doctrine/collections"
      - dependency-name: "doctrine/dbal"
      - dependency-name: "doctrine/orm"
      - dependency-name: "doctrine/persistence"
      - dependency-name: "fakerphp/faker"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "composer"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
